#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-xml2
Version  : 1.3.6
Release  : 106
URL      : https://cran.r-project.org/src/contrib/xml2_1.3.6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/xml2_1.3.6.tar.gz
Summary  : Parse XML
Group    : Development/Tools
License  : MIT
Requires: R-xml2-lib = %{version}-%{release}
Requires: R-cli
Requires: R-rlang
BuildRequires : R-cli
BuildRequires : R-rlang
BuildRequires : buildreq-R
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : xz-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Built on top of the 'libxml2' C library.

%package lib
Summary: lib components for the R-xml2 package.
Group: Libraries

%description lib
lib components for the R-xml2 package.


%prep
%setup -q -n xml2
pushd ..
cp -a xml2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1701832444

%install
export SOURCE_DATE_EPOCH=1701832444
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/xml2/DESCRIPTION
/usr/lib64/R/library/xml2/INDEX
/usr/lib64/R/library/xml2/LICENSE
/usr/lib64/R/library/xml2/Meta/Rd.rds
/usr/lib64/R/library/xml2/Meta/features.rds
/usr/lib64/R/library/xml2/Meta/hsearch.rds
/usr/lib64/R/library/xml2/Meta/links.rds
/usr/lib64/R/library/xml2/Meta/nsInfo.rds
/usr/lib64/R/library/xml2/Meta/package.rds
/usr/lib64/R/library/xml2/Meta/vignette.rds
/usr/lib64/R/library/xml2/NAMESPACE
/usr/lib64/R/library/xml2/NEWS.md
/usr/lib64/R/library/xml2/R/xml2
/usr/lib64/R/library/xml2/R/xml2.rdb
/usr/lib64/R/library/xml2/R/xml2.rdx
/usr/lib64/R/library/xml2/doc/index.html
/usr/lib64/R/library/xml2/doc/modification.R
/usr/lib64/R/library/xml2/doc/modification.Rmd
/usr/lib64/R/library/xml2/doc/modification.html
/usr/lib64/R/library/xml2/extdata/cd_catalog.xml
/usr/lib64/R/library/xml2/extdata/order-doc.xml
/usr/lib64/R/library/xml2/extdata/order-schema.xml
/usr/lib64/R/library/xml2/extdata/r-project.html
/usr/lib64/R/library/xml2/help/AnIndex
/usr/lib64/R/library/xml2/help/aliases.rds
/usr/lib64/R/library/xml2/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/xml2/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/xml2/help/paths.rds
/usr/lib64/R/library/xml2/help/xml2.rdb
/usr/lib64/R/library/xml2/help/xml2.rdx
/usr/lib64/R/library/xml2/html/00Index.html
/usr/lib64/R/library/xml2/html/R.css
/usr/lib64/R/library/xml2/include/xml2_types.h
/usr/lib64/R/library/xml2/tests/testthat.R
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_attr.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_children.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_document.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_find.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_name.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_node.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_nodeset.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_parse.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_structure.md
/usr/lib64/R/library/xml2/tests/testthat/_snaps/xml_write.md
/usr/lib64/R/library/xml2/tests/testthat/helper.R
/usr/lib64/R/library/xml2/tests/testthat/lego.html.bz2
/usr/lib64/R/library/xml2/tests/testthat/ns-multiple-aliases.xml
/usr/lib64/R/library/xml2/tests/testthat/ns-multiple-default.xml
/usr/lib64/R/library/xml2/tests/testthat/ns-multiple-prefix.xml
/usr/lib64/R/library/xml2/tests/testthat/ns-multiple.xml
/usr/lib64/R/library/xml2/tests/testthat/records.dtd
/usr/lib64/R/library/xml2/tests/testthat/records.xml
/usr/lib64/R/library/xml2/tests/testthat/setup.R
/usr/lib64/R/library/xml2/tests/testthat/test-as_list.R
/usr/lib64/R/library/xml2/tests/testthat/test-as_xml_document.R
/usr/lib64/R/library/xml2/tests/testthat/test-classes.R
/usr/lib64/R/library/xml2/tests/testthat/test-format.R
/usr/lib64/R/library/xml2/tests/testthat/test-null.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_attr.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_children.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_document.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_find.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_missing.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_modify.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_name.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_namespaces.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_node.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_nodeset.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_parse.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_schema.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_serialize.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_structure.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_text.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_type.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_url.R
/usr/lib64/R/library/xml2/tests/testthat/test-xml_write.R
/usr/lib64/R/library/xml2/tests/testthat/xml

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/xml2/libs/xml2.so
/usr/lib64/R/library/xml2/libs/xml2.so.avx2
/usr/lib64/R/library/xml2/libs/xml2.so.avx512
